<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
<xacro:include filename="$(find hunter_description)/description/wheel.urdf.xacro"/>
<xacro:macro name="dogbot" params="prefix:='' is_sim:=true">
     <!-- Base Size -->
    <xacro:property name="base_x_size" value="0.98740000" />
    <xacro:property name="base_y_size" value="0.57090000" />
    <xacro:property name="base_z_size" value="0.24750000" />

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheelbase" value="0.5120" />
    <xacro:property name="track" value="0.4908" />   <!-- Original 0.5708, after 0.4908 -->
    <xacro:property name="wheel_vertical_offset" value="0.03282" />

    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.27" />  <!--  0.27 -->
    <xacro:property name="wheel_radius" value="0.137" /> <!--  0.137 -->

    <xacro:property name="hunter_front_bumper_extend" value="0" />
    <xacro:property name="hunter_rear_bumper_extend" value="0" />

    <xacro:property name="M_PI" value="3.14159"/>


    <!-- Base link is the center of the robot's bottom plate -->

    <link name="${prefix}base_link">
      <visual>
        <origin xyz="-0.05 0 0.12" rpy="0 0 0" />  <!-- HERREEEEE--> <!-- 0.18-->
        <geometry>
          <!-- <mesh filename="package://husky_description/meshes/base_link.dae" /> -->
          <mesh filename="file://$(find hunter_description)/meshes/chassis.dae" /> 
          <!--<box size="${ base_x_size + hunter_front_bumper_extend + hunter_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>-->
        </geometry>
      </visual>
      <collision>
        <origin xyz="${( hunter_front_bumper_extend - hunter_rear_bumper_extend ) / 2.0} 0 ${base_z_size/4}" rpy="0 0 0" />
        <geometry>
          <box size="${ base_x_size + hunter_front_bumper_extend + hunter_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="${prefix}base_footprint"/>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}base_footprint" />
    </joint>

    <!-- Inertial link stores the robot's inertial information -->
    <link name="${prefix}inertial_link">
      <inertial>
        <mass value="1.034" />
        <origin xyz="-0.00065 -0.085 0.062" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="${prefix}inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}inertial_link" />
    </joint>

    

    <xacro:hunter_wheel wheel_prefix="${prefix}front_left" x="${wheelbase/2}" y="${track/2}" z="${wheel_vertical_offset}" is_sim="${is_sim}"/>
    <xacro:hunter_wheel wheel_prefix="${prefix}front_right" x="${wheelbase/2}" y="${-track/2}" z="${wheel_vertical_offset}" is_sim="${is_sim}"/>
    <xacro:hunter_wheel wheel_prefix="${prefix}back_left" x="${-wheelbase/2}" y="${track/2}" z="${wheel_vertical_offset}" is_sim="${is_sim}"/>
    <xacro:hunter_wheel wheel_prefix="${prefix}back_right" x="${-wheelbase/2}" y="${-track/2}" z="${wheel_vertical_offset}" is_sim="${is_sim}"/>
</xacro:macro>
</robot>
